services:
  - type: web
    name: roblox-login-bot
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: docker build -t roblox-login-bot .
    startCommand: docker run -p $PORT:8000 roblox-login-bot 