services:
  - type: web
    name: roblox-login-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /health
    autoDeploy: true 